version: '3.6'
services:
  db:
    image: mongo:4.2
    container_name: mongo
    volumes:     
      - dbdata:/data/db
    networks:
      - app-network
  nodejs:
    build: .
    ports:
      - "3071:3071"
    networks:
      - app-network
    command: node index.js
networks:
  app-network:
volumes:
  dbdata: