version: '3.6'
services:
  mk-mongo:
    image: mongo:4.2
    container_name: mk-mongo
    volumes:     
      - dbdata:/data/db
    networks:
      - mk-app-network
  nodejs:
    build: .
    ports:
      - "3071:3071"
    networks:
      - mk-app-network
    command: node index.js
networks:
  mk-app-network:
volumes:
  dbdata: